---
# tasks file for virtual_machene
#
- name: copy helthcheck template
  template:
    src:  virtual.j2
    dest: /tmp/{{  ansible_default_ipv4.address  }}_helthcheck.xml
    mode: 0740

- name: Disk Space
  shell:  df -h >> /tmp/{{  ansible_default_ipv4.address  }}_helthcheck.xml

- name: Install expect
  package:
    name: expect
    state:  present

- name: Coppy helthcheck file
  template:
    src:  scp.j2
    dest: scp.expect
    mode: 0740

- name: download {{  ansible_default_ipv4.address  }}_helthcheck.xml file
  shell:  ./scp.expect
  
